version: 2.1
jobs:
  build:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: npm install
    - run:
        name: Run the App
        command: npm start
    - run:
        name: Stop the App
        command: killall node

  test:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run:
        name: Run the tests
        command: npm run test




workflows:
  version: 2
  build_test_exec:
    jobs:
    - build
    - test:
        requires:
        - build
