version: 2.1
jobs:
  build:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: npm install
    - run:
        name: Run the app
        command: npm start
  test:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run:
        name: Run the tests
        command: npm run test


workflows:
  version: 2
  build_and_test:
    jobs:
    - build:
        requires:
        - test
    - test
